"""Strategist Agent - Strategy generation and signal creation."""

import json
import re
from dataclasses import dataclass, asdict
from datetime import datetime
from enum import Enum
from typing import Any

from quant_agent.agents.base import AgentRole, BaseAgent
from quant_agent.core.llm import LLMProvider
from quant_agent.core.memory import AgentMemory, MemoryType


class SignalType(Enum):
    """Types of trading signals."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


def _is_valid_bracket_structure(
    signal_type: SignalType,
    entry_price: float | None,
    stop_loss: float | None,
    target_price: float | None,
) -> bool:
    if signal_type == SignalType.HOLD or entry_price is None or entry_price <= 0:
        return True
    if stop_loss is None or target_price is None:
        return False
    if signal_type == SignalType.BUY:
        return stop_loss < entry_price < target_price
    return target_price < entry_price < stop_loss


def _normalize_brackets(
    signal_type: SignalType,
    entry_price: float | None,
    stop_loss: float | None,
    target_price: float | None,
    *,
    default_stop_loss_pct: float,
    risk_reward_ratio: float,
) -> tuple[float | None, float | None]:
    if signal_type == SignalType.HOLD or entry_price is None or entry_price <= 0:
        return stop_loss, target_price

    numeric_levels = [
        float(level)
        for level in (stop_loss, target_price)
        if level is not None and float(level) > 0
    ]
    minimum_risk = max(entry_price * 0.005, 0.01)

    if signal_type == SignalType.BUY:
        below_entry = sorted(level for level in numeric_levels if level < entry_price)
        above_entry = sorted(level for level in numeric_levels if level > entry_price)
        normalized_stop = below_entry[-1] if below_entry else entry_price * (1 - default_stop_loss_pct)
        risk = max(entry_price - normalized_stop, minimum_risk)
        normalized_target = above_entry[0] if above_entry else entry_price + (risk * risk_reward_ratio)
        if normalized_target <= entry_price:
            normalized_target = entry_price + (risk * risk_reward_ratio)
        if normalized_stop >= entry_price:
            normalized_stop = entry_price - risk
        return normalized_stop, normalized_target

    above_entry = sorted(level for level in numeric_levels if level > entry_price)
    below_entry = sorted(level for level in numeric_levels if level < entry_price)
    normalized_stop = above_entry[0] if above_entry else entry_price * (1 + default_stop_loss_pct)
    risk = max(normalized_stop - entry_price, minimum_risk)
    normalized_target = below_entry[-1] if below_entry else entry_price - (risk * risk_reward_ratio)
    if normalized_target >= entry_price:
        normalized_target = entry_price - (risk * risk_reward_ratio)
    if normalized_stop <= entry_price:
        normalized_stop = entry_price + risk
    return normalized_stop, normalized_target


@dataclass
class TradingSignal:
    """A trading signal generated by the strategist."""

    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    entry_price: float | None
    target_price: float | None
    stop_loss: float | None
    rationale: str
    timeframe: str  # short, medium, long
    risk_reward_ratio: float
    position_size_pct: float
    metadata: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "rationale": self.rationale,
            "timeframe": self.timeframe,
            "risk_reward_ratio": self.risk_reward_ratio,
            "position_size_pct": self.position_size_pct,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "TradingSignal":
        signal_type_raw = str(data.get("signal_type", "hold")).lower()
        signal_type = {
            "buy": SignalType.BUY,
            "sell": SignalType.SELL,
            "hold": SignalType.HOLD,
        }.get(signal_type_raw, SignalType.HOLD)
        entry_price = _as_optional_float(data.get("entry_price"))
        stop_loss = _as_optional_float(data.get("stop_loss"))
        target_price = _as_optional_float(data.get("target_price"))
        stop_loss, target_price = _normalize_brackets(
            signal_type,
            entry_price,
            stop_loss,
            target_price,
            default_stop_loss_pct=StrategistAgent.DEFAULT_STOP_LOSS_PCT,
            risk_reward_ratio=StrategistAgent.MIN_RISK_REWARD_RATIO,
        )

        return cls(
            symbol=str(data.get("symbol", "")),
            signal_type=signal_type,
            confidence=float(data.get("confidence", 0.0)),
            entry_price=entry_price,
            target_price=target_price,
            stop_loss=stop_loss,
            rationale=str(data.get("rationale", "")),
            timeframe=str(data.get("timeframe", "medium")),
            risk_reward_ratio=float(data.get("risk_reward_ratio", 0.0)),
            position_size_pct=float(data.get("position_size_pct", 0.0)),
            metadata=dict(data.get("metadata", {})),
        )


def _as_optional_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


class StrategistAgent(BaseAgent):
    """
    Strategist Agent responsibilities:
    - Generate trading signals based on research
    - Define entry/exit points with precision
    - Set target prices and stop losses
    - Validate strategies against historical data
    - Calculate position sizes based on risk
    """

    # Strategy parameters
    MIN_RISK_REWARD_RATIO = 2.0
    MIN_CONFIDENCE = 0.6
    MAX_POSITION_PCT = 0.10  # 10% max per position
    DEFAULT_STOP_LOSS_PCT = 0.05  # 5% default stop
    RULE_RISK_PCT = 0.01  # 1% risk per trade

    def __init__(self, llm: LLMProvider, memory: AgentMemory | None = None):
        super().__init__(AgentRole.STRATEGIST, llm, memory)

    @property
    def system_prompt(self) -> str:
        return """You are a Strategist Agent specializing in quantitative trading strategies.

Your responsibilities:
1. Generate trading signals (buy/sell/hold) based on research
2. Define precise entry and exit points
3. Calculate appropriate target prices and stop losses
4. Validate strategies against risk parameters
5. Determine optimal position sizes

Guidelines:
- Always provide confidence levels (0-1)
- Require minimum 2:1 risk/reward ratio for trades
- Factor in market conditions and volatility
- Quality over quantity - avoid overtrading

Signal Criteria:
- BUY: Clear upward momentum, positive sentiment, technical confirmation
- SELL: Downward pressure, negative signals, risk threshold met
- HOLD: Unclear direction, high volatility, or insufficient edge

Risk Management:
- Calculate position size based on risk per trade (max 2% of capital)
- Set stop losses at technical levels (support/resistance, ATR-based)
- Consider correlation between positions
- Account for market regime (bull/bear/sideways)

Response Format:
Always respond in valid JSON with these fields:
{
    "signal_type": "buy|sell|hold",
    "confidence": 0.0-1.0,
    "entry_price": number,
    "target_price": number,
    "stop_loss": number,
    "timeframe": "short|medium|long",
    "rationale": "detailed explanation",
    "risk_factors": ["list of risks"],
    "confirmation_signals": ["list of confirming indicators"]
}"""

    async def execute(self, task: str, **kwargs: Any) -> dict[str, Any]:
        """Execute a strategy task."""
        if task == "generate_signals":
            return await self._generate_signals(kwargs.get("research_data"))
        elif task == "validate_strategy":
            return await self._validate_strategy(kwargs.get("strategy"))
        elif task == "optimize_entry":
            return await self._optimize_entry(
                kwargs.get("symbol"),
                kwargs.get("signal_type"),
                kwargs.get("market_data"),
            )
        elif task == "calculate_position_size":
            return await self._calculate_position_size(
                kwargs.get("signal"),
                kwargs.get("capital"),
                kwargs.get("atr"),
            )
        else:
            return {"error": f"Unknown task: {task}"}

    async def _generate_signals(self, research_data: dict[str, Any]) -> dict[str, Any]:
        """Generate trading signals based on research data."""
        signals: list[TradingSignal] = []

        for symbol, data in research_data.get("symbols", {}).items():
            signal = await self._analyze_and_generate_signal(symbol, data)
            if signal and signal.signal_type != SignalType.HOLD:
                signals.append(signal)

        # Rank signals by confidence * risk-reward
        signals.sort(
            key=lambda s: s.confidence * s.risk_reward_ratio,
            reverse=True,
        )

        # Store signals in memory
        self.memory.add(
            MemoryType.SIGNAL,
            content={"signals": [s.to_dict() for s in signals]},
            metadata={"count": len(signals), "timestamp": datetime.now().isoformat()},
            importance=0.9,
        )

        return {
            "signals": [s.to_dict() for s in signals],
            "total_signals": len(signals),
            "buy_signals": len([s for s in signals if s.signal_type == SignalType.BUY]),
            "sell_signals": len([s for s in signals if s.signal_type == SignalType.SELL]),
            "timestamp": datetime.now().isoformat(),
        }

    async def _analyze_and_generate_signal(
        self, symbol: str, data: dict[str, Any]
    ) -> TradingSignal | None:
        """Analyze research data and generate a signal for a symbol."""
        analysis = data.get("analysis", {})
        indicators = analysis.get("indicators", {})
        sentiment = analysis.get("sentiment", {})
        stock_info = analysis.get("stock_info", {})

        # Get current price from market data
        market_data = analysis.get("market_data", {})
        data_points = market_data.get("data", [])
        current_price = data_points[-1].get("Close", 0) if data_points else 0

        if current_price == 0:
            return None

        rule_signal = self._generate_rule_based_signal(symbol, analysis, current_price)
        if self.context.strategy.lower() in {"fortress", "quant_trading_cn", "vwap_pullback", "orb"}:
            return rule_signal
        if rule_signal and rule_signal.signal_type != SignalType.HOLD:
            return rule_signal

        # Build comprehensive prompt
        prompt = f"""Analyze the following data for {symbol} and generate a trading signal:

CURRENT PRICE: ${current_price:.2f}

TECHNICAL INDICATORS:
- SMA 20: {indicators.get('sma_20', ['N/A'])[-1] if indicators.get('sma_20') else 'N/A'}
- SMA 50: {indicators.get('sma_50', ['N/A'])[-1] if indicators.get('sma_50') else 'N/A'}
- RSI: {indicators.get('rsi', ['N/A'])[-1] if indicators.get('rsi') else 'N/A'}
- MACD: {indicators.get('macd', ['N/A'])[-1] if indicators.get('macd') else 'N/A'}

SENTIMENT:
- Overall: {sentiment.get('sentiment', 'N/A')}
- Score: {sentiment.get('score', 'N/A')}

FUNDAMENTALS:
- P/E Ratio: {stock_info.get('pe_ratio', 'N/A')}
- Market Cap: ${stock_info.get('market_cap', 0):,.0f}
- Beta: {stock_info.get('beta', 'N/A')}

INSIGHTS: {data.get('insights', 'N/A')}

Generate a trading signal with precise entry, target, and stop loss levels.
Focus on risk-adjusted returns with minimum 2:1 risk/reward ratio."""

        response = await self.think(prompt)
        signal = self._parse_signal_response(symbol, response, current_price)

        return signal

    def _generate_rule_based_signal(
        self,
        symbol: str,
        analysis: dict[str, Any],
        current_price: float,
    ) -> TradingSignal:
        strategy_name = self.context.strategy.lower()
        if strategy_name in {"quant_trading_cn", "fortress"}:
            return self._generate_fortress_signal(symbol, analysis, current_price)
        if strategy_name == "vwap_pullback":
            return self._generate_vwap_pullback_signal(symbol, analysis, current_price)
        if strategy_name == "orb":
            return self._generate_orb_signal(symbol, analysis, current_price)
        return self._generate_fortress_signal(symbol, analysis, current_price)

    def _generate_fortress_signal(
        self,
        symbol: str,
        analysis: dict[str, Any],
        current_price: float,
    ) -> TradingSignal:
        indicators = analysis.get("indicators", {})
        sentiment = analysis.get("sentiment", {})
        market_data = analysis.get("market_data", {})
        data_points = market_data.get("data", [])
        latest_bar = data_points[-1] if data_points else {}

        ema_9 = self._latest_indicator(indicators, "ema_9")
        ema_21 = self._latest_indicator(indicators, "ema_21")
        rsi = self._latest_indicator(indicators, "rsi")
        adx = self._latest_indicator(indicators, "adx_14")
        vwap = self._latest_indicator(indicators, "vwap")
        avg_volume = self._latest_indicator(indicators, "avg_volume")
        body_pct = self._latest_indicator(indicators, "body_pct")
        atr = self._latest_indicator(indicators, "atr_14") or (current_price * 0.02)
        macd = self._latest_indicator(indicators, "macd")
        macd_signal = self._latest_indicator(indicators, "macd_signal")
        volume = float(latest_bar.get("Volume", 0) or 0)
        sentiment_score = float(sentiment.get("score", 0.5) or 0.5)

        bullish_checks = {
            "ema_trend": ema_9 is not None and ema_21 is not None and ema_9 > ema_21,
            "vwap": vwap is not None and current_price > vwap,
            "adx": adx is not None and adx > 25,
            "rsi": rsi is not None and 45 <= rsi <= 65,
            "volume": avg_volume is not None and avg_volume > 0 and volume > avg_volume * 1.2,
            "body": body_pct is not None and body_pct > 0.25,
            "macd": macd is not None and macd_signal is not None and macd > macd_signal,
            "sentiment": sentiment_score >= 0.55,
        }
        bearish_checks = {
            "ema_trend": ema_9 is not None and ema_21 is not None and ema_9 < ema_21,
            "vwap": vwap is not None and current_price < vwap,
            "adx": adx is not None and adx > 25,
            "rsi": rsi is not None and 35 <= rsi <= 55,
            "volume": avg_volume is not None and avg_volume > 0 and volume > avg_volume * 1.2,
            "body": body_pct is not None and body_pct > 0.25,
            "macd": macd is not None and macd_signal is not None and macd < macd_signal,
            "sentiment": sentiment_score <= 0.45,
        }
        weights = {
            "ema_trend": 0.2,
            "vwap": 0.15,
            "adx": 0.15,
            "rsi": 0.1,
            "volume": 0.1,
            "body": 0.1,
            "macd": 0.1,
            "sentiment": 0.1,
        }

        bullish_score = sum(weights[key] for key, passed in bullish_checks.items() if passed)
        bearish_score = sum(weights[key] for key, passed in bearish_checks.items() if passed)
        bullish_factors = [name for name, passed in bullish_checks.items() if passed]
        bearish_factors = [name for name, passed in bearish_checks.items() if passed]

        direction = SignalType.HOLD
        score = 0.0
        factors: list[str] = []
        if bullish_score >= 0.55 and len(bullish_factors) >= 4 and bullish_score > bearish_score:
            direction = SignalType.BUY
            score = bullish_score
            factors = bullish_factors
        elif bearish_score >= 0.55 and len(bearish_factors) >= 4:
            direction = SignalType.SELL
            score = bearish_score
            factors = bearish_factors
        else:
            return self._create_hold_signal(
                symbol,
                (
                    f"Fortress filters not met. bullish={bullish_score:.2f} ({', '.join(bullish_factors) or 'none'}), "
                    f"bearish={bearish_score:.2f} ({', '.join(bearish_factors) or 'none'})"
                ),
            )

        stop_distance = max(atr * 1.5, current_price * 0.02)
        if direction == SignalType.BUY:
            stop_loss = current_price - stop_distance
            target_price = current_price + (stop_distance * self.MIN_RISK_REWARD_RATIO)
        else:
            stop_loss = current_price + stop_distance
            target_price = current_price - (stop_distance * self.MIN_RISK_REWARD_RATIO)

        position_size_pct = self._position_size_pct(current_price, stop_loss, score)
        kelly_fraction = self._kelly_fraction(score, self.MIN_RISK_REWARD_RATIO)

        adx_text = f"{adx:.2f}" if adx is not None else "n/a"
        rsi_text = f"{rsi:.2f}" if rsi is not None else "n/a"
        vwap_text = f"{vwap:.2f}" if vwap is not None else "n/a"
        rationale = (
            f"Fortress rule signal with score {score:.2f}. "
            f"Triggered by: {', '.join(factors)}. "
            f"ADX={adx_text}, RSI={rsi_text}, VWAP={vwap_text}, volume={volume:.0f}."
        )
        return self._build_rule_signal(
            symbol=symbol,
            direction=direction,
            current_price=current_price,
            stop_loss=stop_loss,
            target_price=target_price,
            confidence=score,
            position_size_pct=position_size_pct,
            rationale=rationale,
            strategy="fortress",
            metadata={
                "score": round(score, 2),
                "factors": factors,
                "atr": atr,
                "adx": adx,
                "rsi": rsi,
                "vwap": vwap,
                "stop_distance": round(stop_distance, 4),
                "partial_exit_at_r": 1.0,
                "trail_after_r": 1.0,
                "time_decay_minutes": 1440,
                "kelly_fraction": round(kelly_fraction, 4),
            },
        )

    def _generate_vwap_pullback_signal(
        self,
        symbol: str,
        analysis: dict[str, Any],
        current_price: float,
    ) -> TradingSignal:
        intraday_data = analysis.get("intraday_market_data", {}).get("data", [])
        intraday_indicators = analysis.get("intraday_indicators", {})
        if len(intraday_data) < 20:
            return self._create_hold_signal(symbol, "VWAP pullback needs more intraday bars")

        latest_bar = intraday_data[-1]
        ema_9 = self._latest_indicator(intraday_indicators, "ema_9")
        ema_21 = self._latest_indicator(intraday_indicators, "ema_21")
        vwap = self._latest_indicator(intraday_indicators, "vwap")
        atr = self._latest_indicator(intraday_indicators, "atr_14") or (current_price * 0.01)
        adx = self._latest_indicator(intraday_indicators, "adx_14")
        rsi = self._latest_indicator(intraday_indicators, "rsi")
        avg_volume = self._latest_indicator(intraday_indicators, "avg_volume")
        volume = float(latest_bar.get("Volume", 0) or 0)

        if vwap is None or ema_9 is None or ema_21 is None:
            return self._create_hold_signal(symbol, "VWAP pullback missing EMA/VWAP data")

        distance_to_vwap_pct = abs(current_price - vwap) / max(vwap, 1) * 100
        bullish = (
            ema_9 > ema_21
            and current_price >= vwap
            and distance_to_vwap_pct <= 0.8
            and (adx or 0) >= 18
            and (rsi or 50) <= 62
            and volume >= (avg_volume or volume) * 0.9
        )
        bearish = (
            ema_9 < ema_21
            and current_price <= vwap
            and distance_to_vwap_pct <= 0.8
            and (adx or 0) >= 18
            and (rsi or 50) >= 38
            and volume >= (avg_volume or volume) * 0.9
        )

        if not bullish and not bearish:
            return self._create_hold_signal(
                symbol,
                f"VWAP pullback filters not met. price={current_price:.2f}, vwap={vwap:.2f}, dist={distance_to_vwap_pct:.2f}%",
            )

        direction = SignalType.BUY if bullish else SignalType.SELL
        stop_distance = max(atr * 1.2, current_price * 0.012)
        stop_loss, target_price = self._compute_brackets(direction, current_price, stop_distance)
        confidence = 0.7 + max(0, 0.15 - distance_to_vwap_pct / 10)
        position_size_pct = self._position_size_pct(current_price, stop_loss, confidence)
        kelly_fraction = self._kelly_fraction(confidence, self.MIN_RISK_REWARD_RATIO)
        rationale = (
            f"VWAP pullback setup. direction={direction.value}, price={current_price:.2f}, "
            f"vwap={vwap:.2f}, ema9={ema_9:.2f}, ema21={ema_21:.2f}, dist={distance_to_vwap_pct:.2f}%."
        )
        return self._build_rule_signal(
            symbol=symbol,
            direction=direction,
            current_price=current_price,
            stop_loss=stop_loss,
            target_price=target_price,
            confidence=confidence,
            position_size_pct=position_size_pct,
            rationale=rationale,
            strategy="vwap_pullback",
            metadata={
                "vwap": vwap,
                "ema_9": ema_9,
                "ema_21": ema_21,
                "adx": adx,
                "rsi": rsi,
                "distance_to_vwap_pct": round(distance_to_vwap_pct, 2),
                "atr": atr,
                "stop_distance": round(stop_distance, 4),
                "partial_exit_at_r": 1.0,
                "trail_after_r": 1.0,
                "time_decay_minutes": 180,
                "kelly_fraction": round(kelly_fraction, 4),
            },
        )

    def _generate_orb_signal(
        self,
        symbol: str,
        analysis: dict[str, Any],
        current_price: float,
    ) -> TradingSignal:
        intraday_data = analysis.get("intraday_market_data", {}).get("data", [])
        intraday_indicators = analysis.get("intraday_indicators", {})
        if len(intraday_data) < 12:
            return self._create_hold_signal(symbol, "ORB needs more opening bars")

        opening_bars = intraday_data[:4]
        orb_high = max(float(bar.get("High", 0) or 0) for bar in opening_bars)
        orb_low = min(float(bar.get("Low", 0) or 0) for bar in opening_bars)
        latest_bar = intraday_data[-1]
        close_price = float(latest_bar.get("Close", current_price) or current_price)
        volume = float(latest_bar.get("Volume", 0) or 0)
        avg_volume = self._latest_indicator(intraday_indicators, "avg_volume")
        vwap = self._latest_indicator(intraday_indicators, "vwap")
        adx = self._latest_indicator(intraday_indicators, "adx_14")
        atr = self._latest_indicator(intraday_indicators, "atr_14") or (current_price * 0.012)

        breakout_long = (
            close_price > orb_high
            and (vwap is None or close_price > vwap)
            and volume >= (avg_volume or volume) * 1.2
            and (adx or 0) >= 20
        )
        breakout_short = (
            close_price < orb_low
            and (vwap is None or close_price < vwap)
            and volume >= (avg_volume or volume) * 1.2
            and (adx or 0) >= 20
        )

        if not breakout_long and not breakout_short:
            return self._create_hold_signal(
                symbol,
                f"ORB filters not met. close={close_price:.2f}, orb_high={orb_high:.2f}, orb_low={orb_low:.2f}.",
            )

        direction = SignalType.BUY if breakout_long else SignalType.SELL
        stop_anchor = orb_low if breakout_long else orb_high
        stop_distance = max(abs(close_price - stop_anchor), atr)
        stop_loss, target_price = self._compute_brackets(direction, close_price, stop_distance)
        confidence = 0.74
        position_size_pct = self._position_size_pct(close_price, stop_loss, confidence)
        kelly_fraction = self._kelly_fraction(confidence, self.MIN_RISK_REWARD_RATIO)
        rationale = (
            f"ORB breakout setup. direction={direction.value}, close={close_price:.2f}, "
            f"orb_high={orb_high:.2f}, orb_low={orb_low:.2f}, vwap={vwap if vwap is not None else 'n/a'}."
        )
        return self._build_rule_signal(
            symbol=symbol,
            direction=direction,
            current_price=close_price,
            stop_loss=stop_loss,
            target_price=target_price,
            confidence=confidence,
            position_size_pct=position_size_pct,
            rationale=rationale,
            strategy="orb",
            metadata={
                "orb_high": orb_high,
                "orb_low": orb_low,
                "vwap": vwap,
                "adx": adx,
                "avg_volume": avg_volume,
                "atr": atr,
                "stop_distance": round(stop_distance, 4),
                "partial_exit_at_r": 1.0,
                "trail_after_r": 1.0,
                "time_decay_minutes": 180,
                "kelly_fraction": round(kelly_fraction, 4),
            },
        )

    def _compute_brackets(
        self,
        direction: SignalType,
        entry_price: float,
        stop_distance: float,
    ) -> tuple[float, float]:
        if direction == SignalType.BUY:
            stop_loss = entry_price - stop_distance
            target_price = entry_price + (stop_distance * self.MIN_RISK_REWARD_RATIO)
        else:
            stop_loss = entry_price + stop_distance
            target_price = entry_price - (stop_distance * self.MIN_RISK_REWARD_RATIO)
        return stop_loss, target_price

    @staticmethod
    def _kelly_fraction(confidence: float, risk_reward_ratio: float) -> float:
        if risk_reward_ratio <= 0:
            return 0.0
        win_prob = min(max(confidence, 0.0), 0.99)
        loss_prob = 1 - win_prob
        kelly = ((risk_reward_ratio * win_prob) - loss_prob) / risk_reward_ratio
        return max(0.0, kelly)

    def _position_size_pct(self, entry_price: float, stop_loss: float, confidence: float) -> float:
        risk_per_share = abs(entry_price - stop_loss)
        capital = self.context.capital if self._context else 100_000.0
        max_risk = capital * self.RULE_RISK_PCT
        shares = max_risk / risk_per_share if risk_per_share > 0 else 0.0
        position_value = shares * entry_price
        kelly_fraction = self._kelly_fraction(confidence, self.MIN_RISK_REWARD_RATIO)
        kelly_cap = min(self.MAX_POSITION_PCT, kelly_fraction * 0.5)
        if kelly_cap <= 0:
            kelly_cap = self.MAX_POSITION_PCT * 0.5
        return min(position_value / capital, kelly_cap)

    def _build_rule_signal(
        self,
        *,
        symbol: str,
        direction: SignalType,
        current_price: float,
        stop_loss: float,
        target_price: float,
        confidence: float,
        position_size_pct: float,
        rationale: str,
        strategy: str,
        metadata: dict[str, Any],
    ) -> TradingSignal:
        stop_loss, target_price = _normalize_brackets(
            direction,
            current_price,
            stop_loss,
            target_price,
            default_stop_loss_pct=self.DEFAULT_STOP_LOSS_PCT,
            risk_reward_ratio=self.MIN_RISK_REWARD_RATIO,
        )
        return TradingSignal(
            symbol=symbol,
            signal_type=direction,
            confidence=min(0.95, max(self.MIN_CONFIDENCE, confidence)),
            entry_price=current_price,
            target_price=round(target_price, 2),
            stop_loss=round(stop_loss, 2),
            rationale=rationale,
            timeframe="medium",
            risk_reward_ratio=self.MIN_RISK_REWARD_RATIO,
            position_size_pct=position_size_pct,
            metadata={"strategy": strategy, **metadata},
        )


    @staticmethod
    def _latest_indicator(indicators: dict[str, Any], key: str) -> float | None:
        values = indicators.get(key)
        if not isinstance(values, list) or not values:
            return None
        for raw in reversed(values):
            try:
                value = float(raw)
            except (TypeError, ValueError):
                continue
            if value == value:
                return value
        return None

    def _parse_signal_response(
        self, symbol: str, response: str, current_price: float
    ) -> TradingSignal | None:
        """Parse LLM response into a TradingSignal object."""
        try:
            # Extract JSON from response
            json_match = re.search(r"\{[^{}]*\}", response, re.DOTALL)
            if not json_match:
                return self._create_hold_signal(symbol, "Could not parse signal response")

            data = json.loads(json_match.group())

            # Parse signal type
            signal_type_str = data.get("signal_type", "hold").lower()
            if signal_type_str == "buy":
                signal_type = SignalType.BUY
            elif signal_type_str == "sell":
                signal_type = SignalType.SELL
            else:
                signal_type = SignalType.HOLD

            # Get prices
            entry_price = float(data.get("entry_price", current_price))
            target_price = data.get("target_price")
            stop_loss = data.get("stop_loss")

            # Calculate default stop loss if not provided
            if stop_loss is None:
                if signal_type == SignalType.BUY:
                    stop_loss = entry_price * (1 - self.DEFAULT_STOP_LOSS_PCT)
                else:
                    stop_loss = entry_price * (1 + self.DEFAULT_STOP_LOSS_PCT)
            else:
                stop_loss = float(stop_loss)

            # Calculate default target if not provided
            if target_price is None:
                if signal_type == SignalType.BUY:
                    # Target = 2x the risk
                    risk = entry_price - stop_loss
                    target_price = entry_price + (risk * self.MIN_RISK_REWARD_RATIO)
                else:
                    risk = stop_loss - entry_price
                    target_price = entry_price - (risk * self.MIN_RISK_REWARD_RATIO)
            else:
                target_price = float(target_price)

            stop_loss, target_price = _normalize_brackets(
                signal_type,
                entry_price,
                stop_loss,
                target_price,
                default_stop_loss_pct=self.DEFAULT_STOP_LOSS_PCT,
                risk_reward_ratio=self.MIN_RISK_REWARD_RATIO,
            )

            # Calculate risk/reward ratio
            if signal_type == SignalType.BUY:
                risk = abs(entry_price - stop_loss)
                reward = abs(target_price - entry_price)
            else:
                risk = abs(stop_loss - entry_price)
                reward = abs(entry_price - target_price)

            risk_reward_ratio = reward / risk if risk > 0 else 0

            # Calculate position size (2% risk per trade)
            risk_per_share = risk
            capital = self.context.capital if self._context else 100000
            max_risk = capital * 0.02
            shares = max_risk / risk_per_share if risk_per_share > 0 else 0
            position_value = shares * entry_price
            position_size_pct = min(position_value / capital, self.MAX_POSITION_PCT)

            return TradingSignal(
                symbol=symbol,
                signal_type=signal_type,
                confidence=float(data.get("confidence", 0.5)),
                entry_price=entry_price,
                target_price=target_price,
                stop_loss=stop_loss,
                rationale=data.get("rationale", ""),
                timeframe=data.get("timeframe", "medium"),
                risk_reward_ratio=risk_reward_ratio,
                position_size_pct=position_size_pct,
                metadata={
                    "risk_factors": data.get("risk_factors", []),
                    "confirmation_signals": data.get("confirmation_signals", []),
                    "brackets_valid": _is_valid_bracket_structure(signal_type, entry_price, stop_loss, target_price),
                    "raw_response": response,
                },
            )

        except (json.JSONDecodeError, ValueError, KeyError, TypeError) as e:
            return self._create_hold_signal(symbol, f"Signal parsing error: {str(e)}")

    def _create_hold_signal(self, symbol: str, reason: str) -> TradingSignal:
        """Create a HOLD signal with explanation."""
        return TradingSignal(
            symbol=symbol,
            signal_type=SignalType.HOLD,
            confidence=0.0,
            entry_price=None,
            target_price=None,
            stop_loss=None,
            rationale=reason,
            timeframe="N/A",
            risk_reward_ratio=0.0,
            position_size_pct=0.0,
            metadata={},
        )

    async def _validate_strategy(self, strategy: dict[str, Any]) -> dict[str, Any]:
        """Validate a strategy against risk parameters."""
        signal = strategy.get("signal")

        validation_issues = []

        # Check risk/reward ratio
        rr_ratio = signal.get("risk_reward_ratio", 0) if signal else 0
        if rr_ratio < self.MIN_RISK_REWARD_RATIO:
            validation_issues.append(f"Risk/reward ratio {rr_ratio:.2f} below minimum {self.MIN_RISK_REWARD_RATIO}")

        # Check confidence
        confidence = signal.get("confidence", 0) if signal else 0
        if confidence < self.MIN_CONFIDENCE:
            validation_issues.append(f"Confidence {confidence:.2f} below minimum {self.MIN_CONFIDENCE}")

        # Check stop loss exists
        if signal and not signal.get("stop_loss"):
            validation_issues.append("No stop loss defined")

        prompt = f"""Validate the following trading strategy:

Strategy: {json.dumps(strategy, indent=2)}

Risk Parameters:
- Minimum Risk/Reward Ratio: {self.MIN_RISK_REWARD_RATIO}
- Minimum Confidence: {self.MIN_CONFIDENCE}
- Maximum Position Size: {self.MAX_POSITION_PCT:.1%}

Issues Identified: {validation_issues}

Provide:
1. Overall validation result (pass/fail)
2. Risk assessment (low/medium/high)
3. Suggested modifications if failing
4. Additional considerations"""

        validation_analysis = await self.think(prompt)

        passed = len(validation_issues) == 0

        return {
            "strategy": strategy,
            "passed": passed,
            "issues": validation_issues,
            "analysis": validation_analysis,
        }

    async def _optimize_entry(
        self, symbol: str, signal_type: str, market_data: dict[str, Any]
    ) -> dict[str, Any]:
        """Optimize entry point for a trade."""
        data_points = market_data.get("data", [])

        prompt = f"""Optimize entry for {signal_type.upper()} signal on {symbol}.

Recent Price Data (last 5 bars):
{json.dumps(data_points[-5:], indent=2) if data_points else 'No data available'}

Consider:
1. Current market conditions and volatility
2. Support and resistance levels
3. Volume profile
4. Time of day effects
5. Order type recommendation (market/limit)

Provide:
1. Optimal entry strategy
2. Recommended order type
3. Entry price range
4. Timing considerations
5. Risk factors"""

        optimization = await self.think(prompt)

        return {
            "symbol": symbol,
            "signal_type": signal_type,
            "optimization": optimization,
            "data_points_analyzed": len(data_points),
        }

    async def _calculate_position_size(
        self, signal: TradingSignal, capital: float, atr: float | None = None
    ) -> dict[str, Any]:
        """Calculate optimal position size based on risk."""
        if signal.entry_price is None or signal.stop_loss is None:
            return {"error": "Cannot calculate position size without entry and stop loss"}

        risk_per_share = abs(signal.entry_price - signal.stop_loss)
        max_risk = capital * 0.02  # 2% risk per trade

        # Calculate shares based on risk
        shares_by_risk = max_risk / risk_per_share if risk_per_share > 0 else 0

        # Calculate shares based on position limit
        max_position_value = capital * self.MAX_POSITION_PCT
        shares_by_limit = max_position_value / signal.entry_price

        # Use the smaller of the two
        shares = min(shares_by_risk, shares_by_limit)
        position_value = shares * signal.entry_price

        return {
            "symbol": signal.symbol,
            "shares": int(shares),
            "position_value": position_value,
            "position_pct": position_value / capital,
            "risk_amount": shares * risk_per_share,
            "risk_pct": (shares * risk_per_share) / capital,
            "entry_price": signal.entry_price,
            "stop_loss": signal.stop_loss,
        }
