"""Strategist Agent - Strategy generation and signal creation."""

import json
import re
from dataclasses import dataclass, asdict
from datetime import datetime
from enum import Enum
from typing import Any

from quant_agent.agents.base import AgentRole, BaseAgent
from quant_agent.core.llm import LLMProvider
from quant_agent.core.memory import AgentMemory, MemoryType


class SignalType(Enum):
    """Types of trading signals."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class TradingSignal:
    """A trading signal generated by the strategist."""

    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 to 1.0
    entry_price: float | None
    target_price: float | None
    stop_loss: float | None
    rationale: str
    timeframe: str  # short, medium, long
    risk_reward_ratio: float
    position_size_pct: float
    metadata: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "symbol": self.symbol,
            "signal_type": self.signal_type.value,
            "confidence": self.confidence,
            "entry_price": self.entry_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "rationale": self.rationale,
            "timeframe": self.timeframe,
            "risk_reward_ratio": self.risk_reward_ratio,
            "position_size_pct": self.position_size_pct,
        }


class StrategistAgent(BaseAgent):
    """
    Strategist Agent responsibilities:
    - Generate trading signals based on research
    - Define entry/exit points with precision
    - Set target prices and stop losses
    - Validate strategies against historical data
    - Calculate position sizes based on risk
    """

    # Strategy parameters
    MIN_RISK_REWARD_RATIO = 2.0
    MIN_CONFIDENCE = 0.6
    MAX_POSITION_PCT = 0.10  # 10% max per position
    DEFAULT_STOP_LOSS_PCT = 0.05  # 5% default stop

    def __init__(self, llm: LLMProvider, memory: AgentMemory | None = None):
        super().__init__(AgentRole.STRATEGIST, llm, memory)

    @property
    def system_prompt(self) -> str:
        return """You are a Strategist Agent specializing in quantitative trading strategies.

Your responsibilities:
1. Generate trading signals (buy/sell/hold) based on research
2. Define precise entry and exit points
3. Calculate appropriate target prices and stop losses
4. Validate strategies against risk parameters
5. Determine optimal position sizes

Guidelines:
- Always provide confidence levels (0-1)
- Require minimum 2:1 risk/reward ratio for trades
- Factor in market conditions and volatility
- Quality over quantity - avoid overtrading

Signal Criteria:
- BUY: Clear upward momentum, positive sentiment, technical confirmation
- SELL: Downward pressure, negative signals, risk threshold met
- HOLD: Unclear direction, high volatility, or insufficient edge

Risk Management:
- Calculate position size based on risk per trade (max 2% of capital)
- Set stop losses at technical levels (support/resistance, ATR-based)
- Consider correlation between positions
- Account for market regime (bull/bear/sideways)

Response Format:
Always respond in valid JSON with these fields:
{
    "signal_type": "buy|sell|hold",
    "confidence": 0.0-1.0,
    "entry_price": number,
    "target_price": number,
    "stop_loss": number,
    "timeframe": "short|medium|long",
    "rationale": "detailed explanation",
    "risk_factors": ["list of risks"],
    "confirmation_signals": ["list of confirming indicators"]
}"""

    async def execute(self, task: str, **kwargs: Any) -> dict[str, Any]:
        """Execute a strategy task."""
        if task == "generate_signals":
            return await self._generate_signals(kwargs.get("research_data"))
        elif task == "validate_strategy":
            return await self._validate_strategy(kwargs.get("strategy"))
        elif task == "optimize_entry":
            return await self._optimize_entry(
                kwargs.get("symbol"),
                kwargs.get("signal_type"),
                kwargs.get("market_data"),
            )
        elif task == "calculate_position_size":
            return await self._calculate_position_size(
                kwargs.get("signal"),
                kwargs.get("capital"),
                kwargs.get("atr"),
            )
        else:
            return {"error": f"Unknown task: {task}"}

    async def _generate_signals(self, research_data: dict[str, Any]) -> dict[str, Any]:
        """Generate trading signals based on research data."""
        signals: list[TradingSignal] = []

        for symbol, data in research_data.get("symbols", {}).items():
            signal = await self._analyze_and_generate_signal(symbol, data)
            if signal and signal.signal_type != SignalType.HOLD:
                signals.append(signal)

        # Rank signals by confidence * risk-reward
        signals.sort(
            key=lambda s: s.confidence * s.risk_reward_ratio,
            reverse=True,
        )

        # Store signals in memory
        self.memory.add(
            MemoryType.SIGNAL,
            content={"signals": [s.to_dict() for s in signals]},
            metadata={"count": len(signals), "timestamp": datetime.now().isoformat()},
            importance=0.9,
        )

        return {
            "signals": [s.to_dict() for s in signals],
            "total_signals": len(signals),
            "buy_signals": len([s for s in signals if s.signal_type == SignalType.BUY]),
            "sell_signals": len([s for s in signals if s.signal_type == SignalType.SELL]),
            "timestamp": datetime.now().isoformat(),
        }

    async def _analyze_and_generate_signal(
        self, symbol: str, data: dict[str, Any]
    ) -> TradingSignal | None:
        """Analyze research data and generate a signal for a symbol."""
        analysis = data.get("analysis", {})
        indicators = analysis.get("indicators", {})
        sentiment = analysis.get("sentiment", {})
        stock_info = analysis.get("stock_info", {})

        # Get current price from market data
        market_data = analysis.get("market_data", {})
        data_points = market_data.get("data", [])
        current_price = data_points[-1].get("Close", 0) if data_points else 0

        if current_price == 0:
            return None

        # Build comprehensive prompt
        prompt = f"""Analyze the following data for {symbol} and generate a trading signal:

CURRENT PRICE: ${current_price:.2f}

TECHNICAL INDICATORS:
- SMA 20: {indicators.get('sma_20', ['N/A'])[-1] if indicators.get('sma_20') else 'N/A'}
- SMA 50: {indicators.get('sma_50', ['N/A'])[-1] if indicators.get('sma_50') else 'N/A'}
- RSI: {indicators.get('rsi', ['N/A'])[-1] if indicators.get('rsi') else 'N/A'}
- MACD: {indicators.get('macd', ['N/A'])[-1] if indicators.get('macd') else 'N/A'}

SENTIMENT:
- Overall: {sentiment.get('sentiment', 'N/A')}
- Score: {sentiment.get('score', 'N/A')}

FUNDAMENTALS:
- P/E Ratio: {stock_info.get('pe_ratio', 'N/A')}
- Market Cap: ${stock_info.get('market_cap', 0):,.0f}
- Beta: {stock_info.get('beta', 'N/A')}

INSIGHTS: {data.get('insights', 'N/A')}

Generate a trading signal with precise entry, target, and stop loss levels.
Focus on risk-adjusted returns with minimum 2:1 risk/reward ratio."""

        response = await self.think(prompt)
        signal = self._parse_signal_response(symbol, response, current_price)

        return signal

    def _parse_signal_response(
        self, symbol: str, response: str, current_price: float
    ) -> TradingSignal | None:
        """Parse LLM response into a TradingSignal object."""
        try:
            # Extract JSON from response
            json_match = re.search(r"\{[^{}]*\}", response, re.DOTALL)
            if not json_match:
                return self._create_hold_signal(symbol, "Could not parse signal response")

            data = json.loads(json_match.group())

            # Parse signal type
            signal_type_str = data.get("signal_type", "hold").lower()
            if signal_type_str == "buy":
                signal_type = SignalType.BUY
            elif signal_type_str == "sell":
                signal_type = SignalType.SELL
            else:
                signal_type = SignalType.HOLD

            # Get prices
            entry_price = float(data.get("entry_price", current_price))
            target_price = data.get("target_price")
            stop_loss = data.get("stop_loss")

            # Calculate default stop loss if not provided
            if stop_loss is None:
                if signal_type == SignalType.BUY:
                    stop_loss = entry_price * (1 - self.DEFAULT_STOP_LOSS_PCT)
                else:
                    stop_loss = entry_price * (1 + self.DEFAULT_STOP_LOSS_PCT)
            else:
                stop_loss = float(stop_loss)

            # Calculate default target if not provided
            if target_price is None:
                if signal_type == SignalType.BUY:
                    # Target = 2x the risk
                    risk = entry_price - stop_loss
                    target_price = entry_price + (risk * self.MIN_RISK_REWARD_RATIO)
                else:
                    risk = stop_loss - entry_price
                    target_price = entry_price - (risk * self.MIN_RISK_REWARD_RATIO)
            else:
                target_price = float(target_price)

            # Calculate risk/reward ratio
            if signal_type == SignalType.BUY:
                risk = abs(entry_price - stop_loss)
                reward = abs(target_price - entry_price)
            else:
                risk = abs(stop_loss - entry_price)
                reward = abs(entry_price - target_price)

            risk_reward_ratio = reward / risk if risk > 0 else 0

            # Calculate position size (2% risk per trade)
            risk_per_share = risk
            capital = self.context.capital if self._context else 100000
            max_risk = capital * 0.02
            shares = max_risk / risk_per_share if risk_per_share > 0 else 0
            position_value = shares * entry_price
            position_size_pct = min(position_value / capital, self.MAX_POSITION_PCT)

            return TradingSignal(
                symbol=symbol,
                signal_type=signal_type,
                confidence=float(data.get("confidence", 0.5)),
                entry_price=entry_price,
                target_price=target_price,
                stop_loss=stop_loss,
                rationale=data.get("rationale", ""),
                timeframe=data.get("timeframe", "medium"),
                risk_reward_ratio=risk_reward_ratio,
                position_size_pct=position_size_pct,
                metadata={
                    "risk_factors": data.get("risk_factors", []),
                    "confirmation_signals": data.get("confirmation_signals", []),
                    "raw_response": response,
                },
            )

        except (json.JSONDecodeError, ValueError, KeyError, TypeError) as e:
            return self._create_hold_signal(symbol, f"Signal parsing error: {str(e)}")

    def _create_hold_signal(self, symbol: str, reason: str) -> TradingSignal:
        """Create a HOLD signal with explanation."""
        return TradingSignal(
            symbol=symbol,
            signal_type=SignalType.HOLD,
            confidence=0.0,
            entry_price=None,
            target_price=None,
            stop_loss=None,
            rationale=reason,
            timeframe="N/A",
            risk_reward_ratio=0.0,
            position_size_pct=0.0,
            metadata={},
        )

    async def _validate_strategy(self, strategy: dict[str, Any]) -> dict[str, Any]:
        """Validate a strategy against risk parameters."""
        signal = strategy.get("signal")

        validation_issues = []

        # Check risk/reward ratio
        rr_ratio = signal.get("risk_reward_ratio", 0) if signal else 0
        if rr_ratio < self.MIN_RISK_REWARD_RATIO:
            validation_issues.append(f"Risk/reward ratio {rr_ratio:.2f} below minimum {self.MIN_RISK_REWARD_RATIO}")

        # Check confidence
        confidence = signal.get("confidence", 0) if signal else 0
        if confidence < self.MIN_CONFIDENCE:
            validation_issues.append(f"Confidence {confidence:.2f} below minimum {self.MIN_CONFIDENCE}")

        # Check stop loss exists
        if signal and not signal.get("stop_loss"):
            validation_issues.append("No stop loss defined")

        prompt = f"""Validate the following trading strategy:

Strategy: {json.dumps(strategy, indent=2)}

Risk Parameters:
- Minimum Risk/Reward Ratio: {self.MIN_RISK_REWARD_RATIO}
- Minimum Confidence: {self.MIN_CONFIDENCE}
- Maximum Position Size: {self.MAX_POSITION_PCT:.1%}

Issues Identified: {validation_issues}

Provide:
1. Overall validation result (pass/fail)
2. Risk assessment (low/medium/high)
3. Suggested modifications if failing
4. Additional considerations"""

        validation_analysis = await self.think(prompt)

        passed = len(validation_issues) == 0

        return {
            "strategy": strategy,
            "passed": passed,
            "issues": validation_issues,
            "analysis": validation_analysis,
        }

    async def _optimize_entry(
        self, symbol: str, signal_type: str, market_data: dict[str, Any]
    ) -> dict[str, Any]:
        """Optimize entry point for a trade."""
        data_points = market_data.get("data", [])

        prompt = f"""Optimize entry for {signal_type.upper()} signal on {symbol}.

Recent Price Data (last 5 bars):
{json.dumps(data_points[-5:], indent=2) if data_points else 'No data available'}

Consider:
1. Current market conditions and volatility
2. Support and resistance levels
3. Volume profile
4. Time of day effects
5. Order type recommendation (market/limit)

Provide:
1. Optimal entry strategy
2. Recommended order type
3. Entry price range
4. Timing considerations
5. Risk factors"""

        optimization = await self.think(prompt)

        return {
            "symbol": symbol,
            "signal_type": signal_type,
            "optimization": optimization,
            "data_points_analyzed": len(data_points),
        }

    async def _calculate_position_size(
        self, signal: TradingSignal, capital: float, atr: float | None = None
    ) -> dict[str, Any]:
        """Calculate optimal position size based on risk."""
        if signal.entry_price is None or signal.stop_loss is None:
            return {"error": "Cannot calculate position size without entry and stop loss"}

        risk_per_share = abs(signal.entry_price - signal.stop_loss)
        max_risk = capital * 0.02  # 2% risk per trade

        # Calculate shares based on risk
        shares_by_risk = max_risk / risk_per_share if risk_per_share > 0 else 0

        # Calculate shares based on position limit
        max_position_value = capital * self.MAX_POSITION_PCT
        shares_by_limit = max_position_value / signal.entry_price

        # Use the smaller of the two
        shares = min(shares_by_risk, shares_by_limit)
        position_value = shares * signal.entry_price

        return {
            "symbol": signal.symbol,
            "shares": int(shares),
            "position_value": position_value,
            "position_pct": position_value / capital,
            "risk_amount": shares * risk_per_share,
            "risk_pct": (shares * risk_per_share) / capital,
            "entry_price": signal.entry_price,
            "stop_loss": signal.stop_loss,
        }
